---
- name: get {{ podman_webserver }} container info
  shell: podman inspect -f {%raw%}"{{.State.Status}}"{%endraw%} {{ podman_webserver }}
  register: container_result
  failed_when: false
  changed_when: false

- name: set {{ podman_webserver }} container state
  set_fact:
    container_exited: "{{ true if container_result.stdout is defined and container_result.stdout == 'exited' else false }}"
    container_running: "{{ true if container_result.stdout is defined and container_result.stdout == 'running' else false }}"
    container_exist: "{{ true if container_result.stdout is defined and container_result.stdout != '' else false }}"
