---
# tasks file for ocp4-bootstrap-webserver

- name: get {{ podman_webserver }} container info
  shell: podman inspect -f {%raw%}"{{.State.Status}}"{%endraw%} {{ podman_webserver }}
  register: container_result
  failed_when: false
  changed_when: false

- name: set {{ podman_webserver }} container state
  set_fact:
    container_exited: "{{ true if container_result.stdout == 'exited' else false }}"
    container_running: "{{ true if container_result.stdout == 'running' else false }}"
    container_notexist: "{{ true if container_result.stdout == '' else false }}"

- name: include download_rhcos_files.yml
  include: download_rhcos_files.yml

- name: include deploy_podman_webserver.yml
  include: deploy_podman_webserver.yml
  when: container_notexist|bool
